dist: trusty
sudo: false
language: node_js
node_js:
  - 10.4.1
cache:
  directories:
    - "node_modules"
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH="$HOME/.yarn/bin:$PATH"
script:
  - yarn test:coverage